name: Build and Publish

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*

  deploy-gh-pages:
    name: Deploy Demo Site to GitHub Pages
    runs-on: ubuntu-latest
    needs: publish-pypi
    steps:
      - uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload test site
        uses: actions/upload-pages-artifact@v2
        with:
          path: ht_serve/testsite

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2