name: Build and Publish

on:
  push:
    branches: [main]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/* || echo "Already uploaded"

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ht_serve/testsite

  deploy-gh-pages:
    name: Deploy Demo Site to GitHub Pages
    runs-on: ubuntu-latest
    needs: publish-pypi
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./site

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
          artifact_name: github-pages